package com.micnubinub.syncthing.model

data class FolderStatus(
    var error: String = "",
    var errors: Long = 0,
    var globalBytes: Long = 0,
    var globalDeleted: Long = 0,
    var globalDirectories: Long = 0,
    var globalFiles: Long = 0,
    var globalSymlinks: Long = 0,
    var globalTotalItems: Long = 0,
    var ignorePatterns: Boolean = false,
    var inSyncBytes: Long = 0,
    var inSyncFiles: Long = 0,
    var invalid: String = "",
    var localBytes: Long = 0,
    var localDeleted: Long = 0,
    var localDirectories: Long = 0,
    var localFiles: Long = 0,
    var localSymlinks: Long = 0,
    var localTotalItems: Long = 0,
    var needBytes: Long = 0,
    var needDeletes: Long = 0,
    var needDirectories: Long = 0,
    var needFiles: Long = 0,
    var needSymlinks: Long = 0,
    var needTotalItems: Long = 0,
    var pullErrors: Long = 0,
    var receiveOnlyChangedBytes: Long = 0,
    var receiveOnlyChangedDeletes: Long = 0,
    var receiveOnlyChangedDirectories: Long = 0,
    var receiveOnlyChangedFiles: Long = 0,
    var receiveOnlyChangedSymlinks: Long = 0,
    var receiveOnlyTotalItems: Long = 0,
    var sequence: Long = 0,
    var state: String = "idle",
    var stateChanged: String = "", // "2019-11-12T20:59:04.9882373Z"
    var version: Long = 0,
    var watchError: String = ""
)
