package com.micnubinub.syncthing.model

/**
 * Sources:
 * - https://github.com/syncthing/syncthing/tree/master/lib/config
 * - https://github.com/syncthing/syncthing/blob/master/lib/config/guiconfiguration.go
 */
data class Gui(
    var enabled: Boolean = true,

    /**
     * REST: useTLS
     * XML: tls
     */
    var useTLS: Boolean = false,
    var address: String? = "127.0.0.1:8384",
    var user: String? = null,
    var password: String? = null,
    var apiKey: String? = null, // Automatically generated by SyncthingNative

    /**
     * Available: default, dark, black
     */
    var theme: String = "default",

    // omitEmpty
    var insecureAdminAccess: Boolean = false,
    var insecureAllowFrameLoading: Boolean = false,
    var insecureSkipHostCheck: Boolean = false
) {
    override fun toString(): String {
        // Redact the password and API key so logs/crash dumps never leak them.
        return "Gui(enabled=$enabled, useTLS=$useTLS, address=$address, user=$user, " +
                "password=***, apiKey=***, theme=$theme, insecureAdminAccess=$insecureAdminAccess, " +
                "insecureAllowFrameLoading=$insecureAllowFrameLoading, " +
                "insecureSkipHostCheck=$insecureSkipHostCheck)"
    }

    val bindAddress: String
        get() {
            if (address == null) {
                return ""
            }
            val split = address?.split(":".toRegex())?.dropLastWhile { it.isEmpty() }
            return if (split?.isEmpty() == true) "" else split?.get(0) ?: ""
        }

    val bindPort: String
        get() {
            if (address == null) {
                return ""
            }
            val split =
                address?.split(":".toRegex())?.dropLastWhile { it.isEmpty() }
            return if ((split?.size ?: 0) < 2) "" else split?.get(1) ?: ""
        }
}
